### ISSUE TITLE
Website front page links and fixes

### ISSUE THREAD

**Issue by ValWood** [geneontology/geneontology.github.io#134]
It looks beautiful found a couple of things slightly confusing.

- [x] It seems odd to have "browse  guides" on the tools icon. This sound like general help.
If you keep this here could it perhaps be labeled more precisely  "browse Tool guides"?

- [x] This page is *very nerdy*  and jargonny http://geneontology.org/docs/tools-guide/

- [x] Citation and Terms
-> Citation ~of~ and Terms of Use.
We use terms differently!

**Comment by lpalbou** [comment]
Hi @ValWood , I have fixed what you asked (for reference: https://github.com/geneontology/geneontology.github.io/pull/140) except the tools-guide page which was an early and quick pass to have something here. It will have to be refined and I intended this page to be indeed a more general guide to GO.

Let me know if you need something else.

**Comment by suzialeksander** [comment]
The "Browse" on Tools & Guides caught my eye again today, it's not fixed so I've unchecked that box.  I totally agree with @ValWood that this is odd.  Maybe "Tools Overview", with the "i" icon to align with the use in the other tabs.  Also, pretty minor, but II suggest the order (for consistency, and to put the related (programmer/GH) :
* Tools Overview
* GO Programmatic Access 
* GO GitHub

**Comment by suzialeksander** [comment]
assigning @lpalbou since I don't know how to change the icon, also after looking it seems like Tools Overview was the intended name since that's the URL:

http://geneontology.org/docs/tools-overview/

**Comment by pgaudet** [comment]
@ValWood @suzialeksander : 
@lpalbou and I renamed some of the items in the boxes on the front page; let us know if that's better, or what other suggestions you have. 

WRT the Programmatic Access to Gene Ontology page- this is intended to programmers so perhaps it's not too cryptic for programmers?

**Comment by lpalbou** [comment]
@suzialeksander we have changed the links but we don't have an amigo icon, it's just the GO icon

@ValWood we have updated the page to state that it's intended to developers but it will need more rework in the future

**Comment by lpalbou** [comment]
For future reference: https://github.com/geneontology/geneontology.github.io/issues/172

**Comment by ValWood** [comment]
Yes it is better, but the default link for tools should be to the biologist friendly overview (i.e when you click the tools icon). I think the problem was that we were seeing this *by default*

**Comment by lpalbou** [comment]
Right, I think you are referring to the links I created on the images to help users explore further the site. I just changed the link of the Tools & Guides image to the more biologist friendly overview http://geneontology.org/docs/tools-overview/
